name: Otros
description: Utiliza esto si ya eres miembro de la organización.
body:
  - type: checkboxes
    attributes:
      label: "Por favor verifica lo siguiente:"
      options:
        - label: Has buscado palabras clave relevantes en [los problemas recientes abiertos y cerrados](https://github.com/todosconectados-gt/todosconectados-gt.github.io/issues?q=is%3Aissue) para evitar duplicados.
          required: true
  - type: textarea
    attributes:
      label: Problema
      placeholder: Describe el problema en detalle
    validations:
      required: true
  - type: textarea
    attributes:
      label: Captura de pantalla (cuando sea necesario)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Solución(es) propuesta(s)
    validations:
      required: false
