name: Primeros Pasos - Pasante Virtual Móvil
description: Utiliza esto si eres un pasante virtual móvil en perspectiva trabajando en nuestros primeros pasos.
labels: ["mi"]
body:
  - type: checkboxes
    attributes:
      label: "Por favor verifica lo siguiente:"
      options:
        - label: Este problema está relacionado con el documento de [Primeros Pasos para Pasantes Móviles](https://todosconectados-gt.github.io/#!pages/mi/mi-10-steps.md) o el [Manual del Usuario de myPlanet](https://todosconectados-gt.github.io/#!pages/manual/myplanet/overview.md).
          required: true
        - label: Has buscado palabras clave relevantes en [los problemas recientes abiertos y cerrados](https://github.com/todosconectados-gt/todosconectados-gt.github.io/issues?q=is%3Aissue) para evitar duplicados.
  - type: input
    attributes:
      label: URL a la página de MDwiki que contiene el problema
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problema
      placeholder: "Describe el problema en detalle."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Captura de pantalla (cuando sea necesario)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Solución(es) propuesta(s)
      placeholder: "Let us know possible changes you'd like to make."
    validations:
      required: true
